# Generated by Django 3.2.13 on 2024-11-19 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('genre_ids', models.JSONField(blank=True, null=True)),
                ('watch_date', models.DateField()),
                ('watch_time', models.CharField(max_length=50)),
                ('watch_place', models.CharField(max_length=50)),
                ('watch_with_who', models.CharField(max_length=50)),
                ('watch_reason', models.JSONField(blank=True, null=True)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('is_share_to_feed', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
