# Generated by Django 3.2.13 on 2024-11-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_experience_feed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('original_title', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('poster_path', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('vote_average', models.FloatField()),
            ],
        ),
    ]
