# Generated by Django 3.2.13 on 2024-11-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_feed_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
