# Generated by Django 3.2.13 on 2024-11-21 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0007_alter_comment_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='emoji',
        ),
        migrations.CreateModel(
            name='Emoji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.IntegerField()),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emoji', to='movies.feed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emoji', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'feed')},
            },
        ),
    ]
